on:
  push:
    paths:
      - Gemfile
      - Gemfile.lock
      - docker-entrypoint.sh
      - update_webdrivers.rb
  workflow_dispatch:
jobs:
  docker-latest:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push (dev mysql8 client)
        id: docker_build_dev_mysql8_client
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: leifcr/rails5-kubernetes:latest
