on: push
jobs:
  docker-dev-mysql8:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push (dev mysql8 client)
        id: docker_build_dev_mysql8_client
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: leifcr/rails5-kubernetes:dev-mysql8-client
          context: ./dev-mysql8/
